site_name: Mirror-based Camera Pose Estimation Using an Orthogonality Constraint
site_description: An Implementation of Takahashi, Nobuhara and Matsuyama "A New Mirror-based Camera Pose Estimation Using an Orthogonality Constraint" presented at CVPR 2012
theme: bootstrap
repo_url: https://github.com/computer-vision/takahashi2012cvpr
extra_javascript: 
    - //cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML
    - mathjax.js
extra_css:
    - custom.css
pages:
    - 'Index': 'index.md'
